export interface StateJurisdictionInfo {
  stateCode: string;
  stateName: string;
  smallClaimsLimitIndividual: number;
  smallClaimsLimitCorporate: number;
  courtName: string;
  securityDepositReturnDays: number;
  securityDepositBadFaithPenaltyMultiplier: number;
  securityDepositStatuteCitation: string;
  statutoryInterestRatePercent: number;
  interestStatuteCitation: string;
  filingFeeEstimate: { min: number; max: number; feeWaiverForm: string; portalUrl: string };
  solWrittenContractYears: number;
  solOralContractYears: number;
  solPropertyDamageYears: number;
  solPersonalInjuryYears: number;
  solConsumerFraudYears: number;
  attorneysAllowedInSmallClaims?: boolean;
}

export const STATE_JURISDICTIONS: Record<string, StateJurisdictionInfo> = {
  CA: {
    stateCode: 'CA',
    stateName: 'California',
    smallClaimsLimitIndividual: 12500,
    smallClaimsLimitCorporate: 6250,
    courtName: 'Superior Court of California, Small Claims Division',
    securityDepositReturnDays: 21,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'Cal. Civ. Code § 1950.5(l)',
    statutoryInterestRatePercent: 10.0,
    interestStatuteCitation: 'Cal. Civ. Code § 3289(b)',
    filingFeeEstimate: { min: 30, max: 75, feeWaiverForm: 'FW-001 (Request for Waiver of Court Fees)', portalUrl: 'https://selfhelp.courts.ca.gov/small-claims' },
    solWrittenContractYears: 4,
    solOralContractYears: 2,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 4,
  },
  NY: {
    stateCode: 'NY',
    stateName: 'New York',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'New York City Civil Court / City Court, Small Claims Part',
    securityDepositReturnDays: 14,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'N.Y. Gen. Oblig. Law § 7-108(1-a)(g)',
    statutoryInterestRatePercent: 9.0,
    interestStatuteCitation: 'N.Y. C.P.L.R. § 5004',
    filingFeeEstimate: { min: 15, max: 20, feeWaiverForm: 'Poor Person Relief (CPLR § 1101)', portalUrl: 'https://nycourts.gov/courts/nyc/civil/smallclaims.shtml' },
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 3,
  },
  TX: {
    stateCode: 'TX',
    stateName: 'Texas',
    smallClaimsLimitIndividual: 20000,
    smallClaimsLimitCorporate: 20000,
    courtName: 'Justice Court (Justice of the Peace), Small Claims',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'Tex. Prop. Code Ann. § 92.109',
    statutoryInterestRatePercent: 6.0,
    interestStatuteCitation: 'Tex. Fin. Code Ann. § 302.002',
    filingFeeEstimate: { min: 54, max: 120, feeWaiverForm: 'Statement of Inability to Afford Payment of Court Costs (TRCP 145)', portalUrl: 'https://www.txcourts.gov/programs-services/self-help/' },
    solWrittenContractYears: 4,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  FL: {
    stateCode: 'FL',
    stateName: 'Florida',
    smallClaimsLimitIndividual: 8000,
    smallClaimsLimitCorporate: 8000,
    courtName: 'County Court, Small Claims Division',
    securityDepositReturnDays: 15,
    securityDepositBadFaithPenaltyMultiplier: 1.0,
    securityDepositStatuteCitation: 'Fla. Stat. § 83.49(3)',
    statutoryInterestRatePercent: 5.5,
    interestStatuteCitation: 'Fla. Stat. § 55.03',
    filingFeeEstimate: { min: 55, max: 300, feeWaiverForm: 'Application for Determination of Civil Indigent Status', portalUrl: 'https://www.flcourts.gov/Resources-Services/Court-Improvement/Self-Help-Information/Small-Claims' },
    solWrittenContractYears: 5,
    solOralContractYears: 4,
    solPropertyDamageYears: 4,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 4,
  },
  IL: {
    stateCode: 'IL',
    stateName: 'Illinois',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 10000,
    courtName: 'Circuit Court, Small Claims Department',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: '765 ILCS 710/1',
    statutoryInterestRatePercent: 9.0,
    interestStatuteCitation: '815 ILCS 205/2',
    filingFeeEstimate: { min: 89, max: 215, feeWaiverForm: 'Application for Waiver of Court Fees (IL Supreme Court Form)', portalUrl: 'https://www.illinoiscourts.gov/self-help/' },
    solWrittenContractYears: 10,
    solOralContractYears: 5,
    solPropertyDamageYears: 5,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 3,
  },
  PA: {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    smallClaimsLimitIndividual: 12000,
    smallClaimsLimitCorporate: 12000,
    courtName: 'Magisterial District Court',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: '68 P.S. § 250.512',
    statutoryInterestRatePercent: 6.0,
    interestStatuteCitation: '41 P.S. § 202',
    filingFeeEstimate: { min: 65, max: 140, feeWaiverForm: 'In Forma Pauperis Petition (Pa.R.C.P. 240)', portalUrl: 'https://www.pacourts.us/learn/representing-yourself' },
    solWrittenContractYears: 4,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 6,
  },
  OH: {
    stateCode: 'OH',
    stateName: 'Ohio',
    smallClaimsLimitIndividual: 6000,
    smallClaimsLimitCorporate: 6000,
    courtName: 'Municipal Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'Ohio Rev. Code § 5321.16(C)',
    statutoryInterestRatePercent: 5.0,
    interestStatuteCitation: 'Ohio Rev. Code § 1343.03',
    filingFeeEstimate: { min: 37, max: 80, feeWaiverForm: 'Financial Disclosure / Fee Waiver Affidavit', portalUrl: 'https://www.supremecourt.ohio.gov/courts/services-for-the-public/' },
    solWrittenContractYears: 6,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  GA: {
    stateCode: 'GA',
    stateName: 'Georgia',
    smallClaimsLimitIndividual: 15000,
    smallClaimsLimitCorporate: 15000,
    courtName: 'Magistrate Court',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'O.C.G.A. § 44-7-35(c)',
    statutoryInterestRatePercent: 7.0,
    interestStatuteCitation: 'O.C.G.A. § 7-4-2',
    filingFeeEstimate: { min: 45, max: 95, feeWaiverForm: 'Pauper’s Affidavit (O.C.G.A. § 9-15-2)', portalUrl: 'https://georgiacourts.gov/self-help/' },
    solWrittenContractYears: 6,
    solOralContractYears: 4,
    solPropertyDamageYears: 4,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  NC: {
    stateCode: 'NC',
    stateName: 'North Carolina',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 10000,
    courtName: 'District Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 1.0,
    securityDepositStatuteCitation: 'N.C. Gen. Stat. § 42-52',
    statutoryInterestRatePercent: 8.0,
    interestStatuteCitation: 'N.C. Gen. Stat. § 24-1',
    filingFeeEstimate: { min: 96, max: 126, feeWaiverForm: 'Petition to Sue/Appeal as an Indigent (AOC-G-106)', portalUrl: 'https://www.nccourts.gov/help-topics/lawsuits-and-small-claims' },
    solWrittenContractYears: 3,
    solOralContractYears: 3,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  WA: {
    stateCode: 'WA',
    stateName: 'Washington',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'District Court, Small Claims Department',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'RCW 59.18.280',
    statutoryInterestRatePercent: 12.0,
    interestStatuteCitation: 'RCW 19.52.010',
    filingFeeEstimate: { min: 35, max: 50, feeWaiverForm: 'Motion and Declaration for Waiver of Civil Fees (GR 34)', portalUrl: 'https://www.courts.wa.gov/newsinfo/resources/' },
    solWrittenContractYears: 6,
    solOralContractYears: 3,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  CO: {
    stateCode: 'CO',
    stateName: 'Colorado',
    smallClaimsLimitIndividual: 7500,
    smallClaimsLimitCorporate: 7500,
    courtName: 'County Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'C.R.S. § 38-12-103',
    statutoryInterestRatePercent: 8.0,
    interestStatuteCitation: 'C.R.S. § 5-12-102',
    filingFeeEstimate: { min: 31, max: 55, feeWaiverForm: 'Motion to File Without Payment of Filing Fee (JDF 205)', portalUrl: 'https://www.courts.state.co.us/Self_Help/smallclaims/' },
    solWrittenContractYears: 3,
    solOralContractYears: 3,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 3,
  },
  AZ: {
    stateCode: 'AZ',
    stateName: 'Arizona',
    smallClaimsLimitIndividual: 3500,
    smallClaimsLimitCorporate: 3500,
    courtName: 'Justice Court, Small Claims Division',
    securityDepositReturnDays: 14,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'A.R.S. § 33-1321(E)',
    statutoryInterestRatePercent: 10.0,
    interestStatuteCitation: 'A.R.S. § 44-1201',
    filingFeeEstimate: { min: 28, max: 62, feeWaiverForm: 'Application for Deferral or Waiver of Court Fees', portalUrl: 'https://www.azcourts.gov/selfservice/' },
    solWrittenContractYears: 6,
    solOralContractYears: 3,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 1,
  },
  MA: {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    smallClaimsLimitIndividual: 7000,
    smallClaimsLimitCorporate: 7000,
    courtName: 'District Court / Boston Municipal Court, Small Claims Session',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'M.G.L. c. 186, § 15B',
    statutoryInterestRatePercent: 12.0,
    interestStatuteCitation: 'M.G.L. c. 231, § 6C',
    filingFeeEstimate: { min: 40, max: 150, feeWaiverForm: 'Affidavit of Indigency (M.G.L. c. 261 § 27B)', portalUrl: 'https://www.mass.gov/info-details/small-claims-court-information' },
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  NJ: {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    smallClaimsLimitIndividual: 5000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'Superior Court of New Jersey, Special Civil Part (Small Claims)',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'N.J.S.A. § 46:8-21.1',
    statutoryInterestRatePercent: 6.0,
    interestStatuteCitation: 'N.J. Court Rule 4:42-11',
    filingFeeEstimate: { min: 35, max: 75, feeWaiverForm: 'Application for Waiver of Court Fees', portalUrl: 'https://www.njcourts.gov/self-help/small-claims' },
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 6,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 6,
  }
};

export function getJurisdiction(stateCode: string): StateJurisdictionInfo {
  return STATE_JURISDICTIONS[stateCode] || STATE_JURISDICTIONS['CA'];
}
