export interface StateJurisdictionInfo {
  stateCode: string;
  stateName: string;
  smallClaimsLimitIndividual: number;
  smallClaimsLimitCorporate: number;
  courtName: string;
  securityDepositReturnDays: number;
  securityDepositBadFaithPenaltyMultiplier: number;
  securityDepositStatuteCitation: string;
  solWrittenContractYears: number;
  solOralContractYears: number;
  solPropertyDamageYears: number;
  solPersonalInjuryYears: number;
  solConsumerFraudYears: number;
}

export const STATE_JURISDICTIONS: Record<string, StateJurisdictionInfo> = {
  CA: {
    stateCode: 'CA',
    stateName: 'California',
    smallClaimsLimitIndividual: 12500,
    smallClaimsLimitCorporate: 6250,
    courtName: 'Superior Court of California, Small Claims Division',
    securityDepositReturnDays: 21,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'Cal. Civ. Code § 1950.5(l)',
    solWrittenContractYears: 4,
    solOralContractYears: 2,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 4,
  },
  NY: {
    stateCode: 'NY',
    stateName: 'New York',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'New York City Civil Court / City Court, Small Claims Part',
    securityDepositReturnDays: 14,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'N.Y. Gen. Oblig. Law § 7-108(1-a)(g)',
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 3,
  },
  TX: {
    stateCode: 'TX',
    stateName: 'Texas',
    smallClaimsLimitIndividual: 20000,
    smallClaimsLimitCorporate: 20000,
    courtName: 'Justice Court (Justice of the Peace), Small Claims',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'Tex. Prop. Code Ann. § 92.109',
    solWrittenContractYears: 4,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  FL: {
    stateCode: 'FL',
    stateName: 'Florida',
    smallClaimsLimitIndividual: 8000,
    smallClaimsLimitCorporate: 8000,
    courtName: 'County Court, Small Claims Division',
    securityDepositReturnDays: 15, // 15 days if no claim, 30 days with claim
    securityDepositBadFaithPenaltyMultiplier: 1.0,
    securityDepositStatuteCitation: 'Fla. Stat. § 83.49(3)',
    solWrittenContractYears: 5,
    solOralContractYears: 4,
    solPropertyDamageYears: 4,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 4,
  },
  IL: {
    stateCode: 'IL',
    stateName: 'Illinois',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 10000,
    courtName: 'Circuit Court, Small Claims Department',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: '765 ILCS 710/1',
    solWrittenContractYears: 10,
    solOralContractYears: 5,
    solPropertyDamageYears: 5,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 3,
  },
  PA: {
    stateCode: 'PA',
    stateName: 'Pennsylvania',
    smallClaimsLimitIndividual: 12000,
    smallClaimsLimitCorporate: 12000,
    courtName: 'Magisterial District Court',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: '68 P.S. § 250.512',
    solWrittenContractYears: 4,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 6,
  },
  OH: {
    stateCode: 'OH',
    stateName: 'Ohio',
    smallClaimsLimitIndividual: 6000,
    smallClaimsLimitCorporate: 6000,
    courtName: 'Municipal Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'Ohio Rev. Code § 5321.16(C)',
    solWrittenContractYears: 6,
    solOralContractYears: 4,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  GA: {
    stateCode: 'GA',
    stateName: 'Georgia',
    smallClaimsLimitIndividual: 15000,
    smallClaimsLimitCorporate: 15000,
    courtName: 'Magistrate Court',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'O.C.G.A. § 44-7-35(c)',
    solWrittenContractYears: 6,
    solOralContractYears: 4,
    solPropertyDamageYears: 4,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 2,
  },
  NC: {
    stateCode: 'NC',
    stateName: 'North Carolina',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 10000,
    courtName: 'District Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 1.0,
    securityDepositStatuteCitation: 'N.C. Gen. Stat. § 42-52',
    solWrittenContractYears: 3,
    solOralContractYears: 3,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  WA: {
    stateCode: 'WA',
    stateName: 'Washington',
    smallClaimsLimitIndividual: 10000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'District Court, Small Claims Department',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'RCW 59.18.280',
    solWrittenContractYears: 6,
    solOralContractYears: 3,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  CO: {
    stateCode: 'CO',
    stateName: 'Colorado',
    smallClaimsLimitIndividual: 7500,
    smallClaimsLimitCorporate: 7500,
    courtName: 'County Court, Small Claims Division',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'C.R.S. § 38-12-103',
    solWrittenContractYears: 3,
    solOralContractYears: 3,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 3,
  },
  AZ: {
    stateCode: 'AZ',
    stateName: 'Arizona',
    smallClaimsLimitIndividual: 3500,
    smallClaimsLimitCorporate: 3500,
    courtName: 'Justice Court, Small Claims Division',
    securityDepositReturnDays: 14,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'A.R.S. § 33-1321(E)',
    solWrittenContractYears: 6,
    solOralContractYears: 3,
    solPropertyDamageYears: 2,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 1,
  },
  MA: {
    stateCode: 'MA',
    stateName: 'Massachusetts',
    smallClaimsLimitIndividual: 7000,
    smallClaimsLimitCorporate: 7000,
    courtName: 'District Court / Boston Municipal Court, Small Claims Session',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 3.0,
    securityDepositStatuteCitation: 'M.G.L. c. 186, § 15B',
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 3,
    solPersonalInjuryYears: 3,
    solConsumerFraudYears: 4,
  },
  NJ: {
    stateCode: 'NJ',
    stateName: 'New Jersey',
    smallClaimsLimitIndividual: 5000,
    smallClaimsLimitCorporate: 5000,
    courtName: 'Superior Court of New Jersey, Special Civil Part (Small Claims)',
    securityDepositReturnDays: 30,
    securityDepositBadFaithPenaltyMultiplier: 2.0,
    securityDepositStatuteCitation: 'N.J.S.A. § 46:8-21.1',
    solWrittenContractYears: 6,
    solOralContractYears: 6,
    solPropertyDamageYears: 6,
    solPersonalInjuryYears: 2,
    solConsumerFraudYears: 6,
  }
};

export function getJurisdiction(stateCode: string): StateJurisdictionInfo {
  return STATE_JURISDICTIONS[stateCode] || STATE_JURISDICTIONS['CA'];
}
